/* Generated by track-cfb.mjs. The College football board's running record. */
window.BETHOUSE_CFB_RECORD = {"days":["2026-08-29"],"total":375,"props":{"td":{"label":"Anytime touchdown","n":266,"predicted":29,"actual":30.5,"bias":-1.4,"brier":0.1956},"recyds":{"label":"Receiving yards, over","n":109,"predicted":40,"actual":44,"bias":-4.1,"brier":0.2492}}};
