#!/usr/bin/env node
/*
 * BetHouse — fetch-teams.mjs
 * ESPN's team lists → `teams-data.js`: each team's two colours, for the
 * stripe on the home's game cards, the tint behind the drawer's hero and
 * the tray cards' left edge (teams.js reads it; DESIGN.md says where a
 * team colour may go and where it may not).
 *
 * Keyless, like every other fetcher here. Three requests, one per league
 * the boards show, keyed the way faces.js keys a team: the NFL and MLB by
 * abbreviation, college by ESPN's numeric team id (the one the game rows
 * carry). A team without a six-hex colour is left out, so a missing
 * colour is a missing stripe; a team whose primary IS black (the
 * Steelers, the Raiders, a third of the FBS) keeps both colours and
 * teams.js paints with the secondary. The MLB rows are written under
 * ESPN's abbreviation and, where statsapi's differs (mlb-data.js keys by
 * statsapi's), under that too.
 *
 * Colours change about once a decade, so this is run by hand and the
 * file is committed; it is not in any refresh workflow.
 *
 *   node fetch-teams.mjs
 */
import { writeFileSync } from "node:fs";

const ESPN = "https://site.api.espn.com/apis/site/v2/sports";
/* `min` is the fewest teams a league can have and still be the league:
   below it the response is partial or reshaped, and the committed file
   is left alone rather than overwritten with a stub. */
const LEAGUES = [
  { league: "NFL", path: "football/nfl", limit: 40, min: 32, key: (t) => t.abbreviation },
  { league: "College football", path: "football/college-football", limit: 1000, min: 100, key: (t) => t.id },
  { league: "MLB", path: "baseball/mlb", limit: 40, min: 30, key: (t) => t.abbreviation, alias: { chw: "cws", ari: "az" } },
];
const HEX = /^[0-9a-f]{6}$/;
const keyOf = (v) => { const k = String(v == null ? "" : v).toLowerCase(); return /^[a-z0-9]{1,8}$/.test(k) ? k : null; };
const hex = (v) => { const h = String(v == null ? "" : v).toLowerCase(); return HEX.test(h) ? h : null; };

async function teams(spec) {
  const res = await fetch(`${ESPN}/${spec.path}/teams?limit=${spec.limit}`);
  if (!res.ok) throw new Error(`${spec.league}: ESPN ${res.status}`);
  const j = await res.json();
  const list = (((j.sports || [])[0] || {}).leagues || [])[0]?.teams || [];
  const out = {};
  let skipped = 0;
  for (const row of list) {
    const t = row.team || {};
    const k = keyOf(spec.key(t)), p = hex(t.color), s = hex(t.alternateColor);
    if (!k || !p) { skipped++; continue; }
    out[k] = s ? { p, s } : { p };
    if (spec.alias && spec.alias[k]) out[spec.alias[k]] = out[k];
  }
  const n = Object.keys(out).length - Object.keys(spec.alias || {}).filter((k) => out[k]).length;
  if (n < spec.min) throw new Error(`${spec.league}: only ${n} teams with a colour (expected at least ${spec.min}); the feed is partial or reshaped, nothing written`);
  console.log(`${spec.league}: ${n} teams with a colour, ${skipped} without`);
  return out;
}

const payload = { generated: new Date().toISOString() };
for (const spec of LEAGUES) payload[spec.league] = await teams(spec);
const js = `/* generated by fetch-teams.mjs from ESPN's team lists — do not edit; re-run to refresh */\nwindow.BetHouseTeamsData = ${JSON.stringify(payload)};\n`;
writeFileSync("teams-data.js", js);
console.log(`teams-data.js: ${js.length.toLocaleString("en-US")} bytes`);
