/* Generated by track-pga.mjs. The golf board's running record. */
window.BETHOUSE_PGA_RECORD = {"days":["2026-09-17"],"total":1,"props":{"cut":{"label":"Makes the cut","n":1,"predicted":64,"actual":0,"bias":64,"brier":0.4092}}};
