/* Generated by track-pga.mjs. The golf board's running record. */
window.BETHOUSE_PGA_RECORD = {"days":["2026-09-17","2026-10-01"],"total":2,"props":{"cut":{"label":"Makes the cut","n":2,"predicted":65.2,"actual":0,"bias":65.2,"brier":0.425}}};
